---
# This role contains sysctrl plays that will run on the nodes provides web servers.

- name: set sysctrl net.ipv4.tcp_fin_timeout
  sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: 35
    state: present

- name: set sysctrl net.ipv4.tcp_keepalive_time
  sysctl:
    name: net.ipv4.tcp_keepalive_time
    value: 1800
    state: present

- name: set sysctrl net.ipv4.tcp_keepalive_intvl
  sysctl:
    name: net.ipv4.tcp_keepalive_intvl
    value: 35
    state: present

- name: set sysctrl net.ipv4.tcp_timestamps
  sysctl:
    name: net.ipv4.tcp_timestamps
    value: 1
    state: present

- name: set sysctrl net.ipv4.tcp_tw_reuse
  sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: 1
    state: present

- name: set sysctrl net.ipv4.tcp_tw_recycle
  sysctl:
    name: net.ipv4.tcp_tw_recycle
    value: 1
    state: present

- name: set sysctrl net.ipv4.tcp_max_tw_buckets
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 5000
    state: present

- name: set sysctrl net.ipv4.tcp_max_tw_buckets
  sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: 5000
    state: present

- name: set sysctrl net.core.wmem_max
  sysctl:
    name: net.core.wmem_max
    value: 134217728
    state: present

- name: set sysctrl net.ipv4.tcp_rmem
  sysctl:
    name: net.ipv4.tcp_rmem
    value: 4096 87380 67108864
    state: present

- name: set sysctrl net.ipv4.tcp_wmem
  sysctl:
    name: net.ipv4.tcp_wmem
    value: 4096 65536 67108864
    state: present

- name: set sysctrl net.core.netdev_max_backlog
  sysctl:
    name: net.core.netdev_max_backlog
    value: 250000
    state: present

- name: set sysctrl net.ipv4.tcp_congestion_control
  sysctl:
    name: net.ipv4.tcp_congestion_control
    value: htcp
    state: present

- name: set sysctrl net.ipv4.tcp_mtu_probing
  sysctl:
    name: net.ipv4.tcp_mtu_probing
    value: 1
    state: present

- name: set transmit queue length
  command: /sbin/ifconfig eth0 txqueuelen 10000
