---
# generate hosts file
- name: "generate /etc/hosts.ansible file"
  template: "src=hosts.j2 dest='/etc/hosts.ansible' owner=root group=root mode=0644"

- name: "backup /etc/hosts"
  command: "cp /etc/hosts /etc/hosts.backup"

- name: "install /etc/hosts.ansible file"
  command: "cp /etc/hosts.ansible /etc/hosts"